# Generated by Django 4.1.3 on 2022-12-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
